- name: Installing Packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - nginx
  notify: start nginx
# I made a loop for a hypothetical case were it should some other packages present

- name: Create a directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /var/www/
    - /var/www/probe_applicant/

- name: Create a Web Page
  template:
    src: local.j2
    dest: "/var/www/local.html"
    mode: '0644'

- name: Create Availability Page
  template:
    src: availability.j2
    dest: "/var/www/probe_applicant/availability.html"
    mode: '0644'

- name: Configure Nginx
  template:
    src: nginx.j2
    dest: "/etc/nginx/nginx.conf"
    mode: '0644'
  notify: reload nginx
