- name: Installing Packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - nginx
  notify: reload nginx

- name: Configuring Nginx
  template:
    src: nginx.j2
    dest: "/etc/nginx/nginx.conf"
    mode: '0644'
