- name: Installing Packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - haproxy
# I made a loop for a hypothetical case were it should some other packages present

- name: Configuring HAproxy
  template:
    src: haproxy.j2
    dest: "/etc/haproxy/haproxy.cfg"
    mode: '0644'
  notify: reload haproxy
