- name: Installing Packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - haproxy

- name: Configuring HAproxy
  template:
    src: haproxy.j2
    dest: "/etc/haproxy/haproxy.conf"
    mode: '0644'
  notify: reload haproxy
