---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install EPEL Repository
    yum:
      name: epel-release
      state: present
  - name: Set SELinux policy to permissive mode
    selinux:
      policy: targeted
      state: permissive
  - name: Stop and disable firewall
    service:
      name: iptables
      state: stopped
      enabled: False
  - name: Disable reboot and shutdown possibility
    file:
      path: "{{ item }}"
      mode: 0644
    loop:
      - /sbin/shutdown
      - /sbin/reboot

- hosts: HAproxy
  become: yes
  become_method: sudo
  tasks:
  - debug:
      msg: "Running HAproxy playbook and roles"
  - include_role:
      name: haproxy
  - debug:
      msg: "Finished HAproxy setup"

- hosts: Nginx
  become: yes
  become_method: sudo
  tasks:
  - debug:
      msg: "Running Nginx playbook and roles"
  - include_role:
      name: nginx
  - debug:
      msg: "Finished Nginx setup"
